adafruit_seesaw/crickit.py

Was 0,1,2,3. Should be 4,5,6,7 per schematic and Learn Guide. Tested.

Correct Crickit touch pin numbers

---

adafruit_seesaw/neopixel.py

1. NeoPixel buffers were not filled correctly.
2. NeoPixel color order not implemented
3. Some code from regular NeoPixel library adapted to here.
Brightness still not implemented.
tagging @ladyada for progress update

neopixel setting fixed

---

adafruit_seesaw/crickit.py
adafruit_seesaw/pwmout.py

1. Redo Crickit pin names in crickit.py. These aren't used anywhere else, but I'm just clarifying the names a bit.
2. Add `PWMOut.fraction`. This allows setting a fractional duty cycle between 0.0 and 1.0 so the user doesn't need to remember 65535 as the upper limit. So for instance, fully on on a Crickit Drive terminal would be 1.0. Used in examples in the https://github.com/adafruit/Adafruit_CircuitPythonCrickit library.

Add .fraction to PWMOut; redo crickit pin names

---

adafruit_seesaw/seesaw.py

Test setup:
Test script:
```python
import time
import board, busio
from adafruit_seesaw.seesaw import Seesaw
i2c = busio.I2C(board.SCL, board.SDA)
ss = Seesaw(i2c, addr=0x36)
start_time = time.time()
count = 0
print("Reading...")
while True:
count += 1
if ss.moisture_read() > 4095:
break
time.sleep(0.1)
print("DONE")
print("count = {}  time = {}".format(count, time.time()-start_time))
```
**BEFORE** :frowning_face: 
```
pi@raspberrypi:~/soil_sensor $ python3 soil_test.py 
Reading...
DONE
count = 223  time = 24.15417194366455
pi@raspberrypi:~/soil_sensor $ python3 soil_test.py 
Reading...
DONE
count = 15  time = 1.5329132080078125
pi@raspberrypi:~/soil_sensor $ python3 soil_test.py 
Reading...
DONE
count = 283  time = 30.68214201927185
pi@raspberrypi:~/soil_sensor $ 
```
**AFTER** :grin: …

Add retries for moisture reading

---

adafruit_seesaw/seesaw.py

temperature reading had been working in the past, but now temperature readings were not being returned correctly. Not sure what changed but increasing the delay for the read fixed the problem.
This delay was already used for the moisture reading.
fixes #33 
Is this possibly due to recent "speedups" in CP in general?  Will other seesaw applications run into similar issues?  Is the default delay of .001 sufficient?
tested on feather_m4_express and pyportal

add delay to I2Cread for temperature reading

---

adafruit_seesaw/seesaw.py

This is a modest adjustment to `pin_mode_bulk` and `pin_mode_bulk_b` which should be functionally equivalent, but avoid duplicated code.

Eliminate duplicated code in pin_mode_bulk*

---

adafruit_seesaw/neopixel.py

Fixes #32. I went with @EricGallimore 's suggestion.
Tested with Crickit HAT on RPi:
```python
pi@crickit:~ $ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board
>>> from adafruit_seesaw.seesaw import Seesaw
>>> from adafruit_seesaw.neopixel import NeoPixel
>>> pixels = NeoPixel(Seesaw(board.I2C()), 20, 8, bpp=4, pixel_order=(1, 0, 2, 3))
>>> pixels.fill(0)
>>> pixels.fill((0,0,0,255))
```

Fix white channel getting set 0.

---

adafruit_seesaw/seesaw.py

This fixes the neotrellis issue (https://github.com/adafruit/circuitpython/issues/2110), so Neotrellis boards now work with the examples. Tested with CircuitPython 5.0 Alpha 3.

Increased default delay because faster cp means it crashes sometimes

---

adafruit_seesaw/analoginput.py
adafruit_seesaw/crickit.py
adafruit_seesaw/digitalio.py
adafruit_seesaw/keypad.py
adafruit_seesaw/neopixel.py
adafruit_seesaw/pwmout.py
adafruit_seesaw/robohat.py
adafruit_seesaw/samd09.py
adafruit_seesaw/seesaw.py
adafruit_seesaw/tftshield18.py
docs/api.rst
docs/conf.py

This completes the documentation to the best of my ability.
Testing performed: built locally and looked at the result.
No functional changes intended.

Improve documentation

---

adafruit_seesaw/digitalio.py
adafruit_seesaw/seesaw.py

.. and fix a problem where direction was not set properly at initialization, and where a "pull" could never actually be set back to None

Digitalio: enable PULL_DOWN mode

---

adafruit_seesaw/seesaw.py

Helps with https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/issues/54. Also added a delay override option for digital_bulk_read() and digital_bulk_read_b(), so more PRs shouldn't be required to slow it down more.

Increase read delay to fix occasional bad reads

---

adafruit_seesaw/keypad.py
adafruit_seesaw/tftshield18.py
examples/seesaw_crickit_test.py
examples/seesaw_joy_featherwing.py
examples/seesaw_minitft_featherwing.py

This directive has been removed from pylint 2.6.0.

remove bad-whitespace pylint directive

---

adafruit_seesaw/tftshield18.py

Fixes #57 -- allows loading tftshield18 on the Raspberry Pi Pico.
Preserves the existing behavior on devices with board.I2C.
The Pico doesn't have a pre-defined I2C, you have to set it up with busio before you can instantiate the TFTShield18 object.
import board
import busio
from adafruit_seesaw.tftshield18 import TFTShield18
i2c_bus = busio.I2C(board.GP3, board.GP2)
shield = TFTShield18(i2c_bus)

Support boards that don't have a fixed I2C bus.

---

adafruit_seesaw/seesaw.py

I noticed there's no existing method for reading the GPIO `INTFLAG`, so I made a quick implementation of it.

Add method for reading GPIO Interrupt flag

---

adafruit_seesaw/seesaw.py
examples/seesaw_rotary_simpletest.py

Add support for rotary encoders and a rotary encoder example.

Add rotary encoder support

---

examples/seesaw_crickit_test.py
examples/seesaw_joy_featherwing.py
examples/seesaw_rotary_simpletest.py
examples/seesaw_simpletest.py
examples/seesaw_soil_simpletest.py

I tested the rotaryio example only.

examples: Use board.I2C()

---

adafruit_seesaw/rotaryio.py
examples/seesaw_rotary_simpletest.py

and also check the product ID as suggested by @jerryneedell from the Arduino example.
The change to the initial value of `last_position` causes the initial position (usually 0) to be printed each time the program starts.

Add a convenience class that mimics rotaryio.IncrementalEncoder in the core

---

adafruit_seesaw/neopixel.py

Fixes a bug that prevents `brightness` from being updated in some cases. I tested this on the QT Rotary Encoder. The test code provided by @kattni.
```py
import time
import board
import busio
from adafruit_seesaw import seesaw, neopixel, rotaryio, digitalio
try:
import _pixelbuf
except ImportError:
import adafruit_pypixelbuf as _pixelbuf
i2c = busio.I2C(board.SCL1, board.SDA1)
seesaw = seesaw.Seesaw(i2c, 0x36)
encoder = rotaryio.IncrementalEncoder(seesaw)
switch = digitalio.DigitalIO(seesaw, 24)
pixel = neopixel.NeoPixel(seesaw, 6, 1)
last_position = -1
color = 0  # start at red
while True:
position = encoder.position
if position != last_position:
print(position)
print(switch.value)
if switch.value:
if position > last_position:  # increase
color += 1
else:
color -= 1
color = (color + 256) …
```

Fix NeoPixel brightness bug

---

examples/seesaw_rotary_neopixel.py
examples/seesaw_rotary_simpletest.py

This updates the rotary examples to:
1.  match imports and setup
2. adds negation so that the encoder position increments when rotated clockwise.
3. adds a pull up to the button pin per the forum suggestion - https://forums.adafruit.com/viewtopic.php?f=19&t=179100#p873311

Update rotary examples

---

adafruit_seesaw/analoginput.py
adafruit_seesaw/seesaw.py

The `seesaw.analog_read()` function has a fixed `time.sleep(0.001)` in addition to the default `time.sleep(0.008)` in `seesaw.read()`.  This PR removes that fixed delay, allows the user to specify the delay used in `read()`, and allows the delay to be specified in the creation of `AnalogInput` objects.  
Tested by @jedgarpark where he was experiencing an accumulated >40 milliseconds of UI lag when reading four NeoSliders.

Propagate delay param from read() to analog_read()

---

adafruit_seesaw/seesaw.py

Pins PA30 and PA31 are the SWDIO and SWDCLK pins. But nothing prevents them from being used as GPIO when a debugger is not connected.
So this PR stops masking the two bits corresponding to these pins so that they can be read if needed. As the user supplied `pins` mask is still applied, this should have no impact on code that was not already trying to read these pins.

Do not blank out the value read for pins PA30 and PA31.

---

adafruit_seesaw/neopixel.py

Simple fix for #101.
This works:
```python
Adafruit CircuitPython 7.2.5 on 2022-04-06; Adafruit Feather M4 Express with samd51j19
>>> import board
>>> from adafruit_seesaw import seesaw, neopixel
>>> ss = seesaw.Seesaw(board.I2C())
>>> pixels = neopixel.NeoPixel(ss, 20, 12, pixel_order=neopixel.GRBW)
>>> pixels.fill(0xFF0000)
>>> 
```
This also works (assumes RGBW pixel order):
```python
Adafruit CircuitPython 7.2.5 on 2022-04-06; Adafruit Feather M4 Express with samd51j19
>>> import board
>>> from adafruit_seesaw import seesaw, neopixel
>>> ss = seesaw.Seesaw(board.I2C())
>>> pixels = neopixel.NeoPixel(ss, 20, 12, bpp=4)
>>> pixels.fill(0xFF0000)
>>> 
```
Trying to over specify incompatible values throws exception:
```python
Adafruit CircuitPython 7.2.5 on 2022-04-06; Adafruit Feather M4 …
```

Fix incorrect RGBW NeoPixel output

---

adafruit_seesaw/neopixel.py
docs/conf.py
requirements.txt

Use PixelBuf to back the pixels buffer in the neopixel submodule.
This adds compatibility with the adafruit_led_animation library, in particular it adds: `__getitem__` and slices support. It sends pixel data all at once, but in chunks to avoid IO errors. It no longer sends pixel data as they are changed. Also switches the pixel order constants to strings, to match the neopixel API.
The size of the chunks is an estimate, I'm not sure if there are devices with seesaw builds that require a smaller size. Sending the whole strip of pixels at once can be quite slow with long pixel strips. This is the only way to do it with PixelBuf however, since the only access to the buffer is in `_transmit`.
Comparatively the original code would send pixels as they are modified, and only send a "show" …

Use pixelbuf

---

adafruit_seesaw/neopixel.py

Using the neokey on a board without builtin adafruit_pixelbuf (using the python version) I get that:
```py
code.py output:
Traceback (most recent call last):
File "code.py", line 9, in <module>
File "adafruit_neokey/neokey1x4.py", line 64, in __init__
File "adafruit_seesaw/neopixel.py", line 80, in __init__
TypeError: unexpected keyword argument 'size'
```
And indeed the size argument is called "n" in that version.
It's the positional argument anyway, no need for a name.

Fix neopixel for python version of adafruit_pixelbuf

---

adafruit_seesaw/seesaw.py

For compatibility on boards that don't support arbitrary integers. Bit 31 and 32 are scrubbed on these boards instead of throwing OverflowError, while builds with long ints retain this extra functionality.
Previous version breaks functionality for boards like QT Py SAMD21 using NeoKey 1x4 QT I2C Breakout or ATSAMD09 Breakout with Seesaw. More details in comments of issue [#107](https://github.com/adafruit/Adafruit_CircuitPython_seesaw/issues/107#issuecomment-1193398747).
Closes: #107

Ignore last 2 bits of digital input, only on boards without long ints

---

adafruit_seesaw/neopixel.py

A common issue is copying the seesaw version of `neopixel.py` into `CIRCUITPY/lib` instead of the "regular" non-seesaw `neopixel.py`. Then, when attempting to run a non-seesaw neopixel example, get:
```
TypeError: function missing required positional argument #4
```
This PR adds a simple path check to the seesaw `neopixel.py` to make sure it is located in a `adafruit_seesaw` folder. This should hopefully throw a more obvious error for the above scenario.
Attempting to import seesaw `neopixel.py` located in `CIRCUITPY/lib`:
```python
Adafruit CircuitPython 7.3.2 on 2022-07-20; Adafruit Metro M4 Airlift Lite with samd51j19
>>> import neopixel
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/lib/neopixel.py", line 23, in <module>
ImportError: seesaw neopixel …
```

Add path check for neopixel.py

---

adafruit_seesaw/attinyx16.py
adafruit_seesaw/seesaw.py

Currently library has incorrect pinmap for newer boards (PIDs 5690 & 5681). This PR adds a new pinmap file and test for it.

Support ATtiny1616 and ATtiny816 boards

---

examples/seesaw_ano_rotary_7segment_demo.py
examples/seesaw_ano_rotary_simpletest.py

Adding two examples for the ANO rotary encoder. Ports of the Arduino example code.

Adding examples for ANO rotary encoder

---

adafruit_seesaw/seesaw.py
examples/seesaw_quadrotary.py

@BlitzCityDIY will need linting n stuffs but is tested on a feather m4

add support for different chip detection + quad rotary demo

---

examples/seesaw_pc_joystick.py

Adding example code for the PC joystick adapter (PID5753)

Adding example for pc joystick

---

adafruit_seesaw/seesaw.py

This is for #122.
**NOTE**: The attempt to dynamically change the address for the underlying I2CDevice has been removed. It was hack that doesn't work. The `device_address` member is not directly accessible anymore now that BusDevice has moved to a builtin library.
Tested using a QT Py RP2040 and a Gamepad STEMMA QT.

Update EEPROM I2C addr for ATtiny seesaw variants

---

adafruit_seesaw/attiny8x7.py
adafruit_seesaw/attinyx16.py
adafruit_seesaw/seesaw.py

For #116 (got issue number wrong in PR fork name)
**NOTE:** The `pwm_pins` for attiny8x7 and attinyx16 have been set to include pins for **both** 8 bit PWM mode and 16 bit PWM mode (a more recent firmware feature). However, only one mode will actually be built into the firmware. There is currently no way to query this from the firmware so that `pwm_pins` could be adjusted at runtime.
Tested on an ATtiny816 seesaw breakout with this code:
```python
import board
from adafruit_seesaw import seesaw
ss = seesaw.Seesaw(board.STEMMA_I2C())
ss.set_pwm_freq(11, 50)
```
**BEFORE**
no output, so waiting forever to trigger
**AFTER**
expected output on pin 11

Fix `set_pwm_freq()` for ATtinys

---

adafruit_seesaw/seesaw.py

Added the hex formatter back to the the chip id error message.

Issue 128: Fixed an error message that was using the wrong number system

---

examples/seesaw_quadrotary.py

Moved `last_position[n] = rotary_pos` to after the `if ( rotary_pos > last_positions[n]):` block. 
Without this, `last_position[n]` was being overwritten before it was compared to `rotary_pos`. This was causing `if ( rotary_pos > last_positions[n]):` to always evaluate to `False` which meant that colors would only move in one direction regardless of if the encoder was rotated clockwise or counterclockwise.

Update seesaw_quadrotary.py to change color of neopixel based on direction of rotation
